global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "23wb-team-b-monitoring"
    metrics_path: /metrics
    static_configs:
      - targets:
          - gtd.kro.kr

  - job_name: "prometheus"
    static_configs:
      - targets:
          - gtd.kro.kr:9090
